-- 요구사항:
-- 1. ETD 기간: 2025년 5월 1일 ~ 2025년 5월 11일
-- 2. POL(출발항) + 컨테이너 타입(CNTR_TYPE) 별로 집계
-- 3. 컨테이너 수량(CNTR 개수) 및 총 중량 합계(CNTR_WGT) 조회
-- 4. 결과 컬럼: POL_CD, CNTR_TYPE, CNTR_COUNT, TOTAL_WGT
-- 5. 정렬: POL_CD, CNTR_TYPE

-- 여기에 SQL 쿼리를 작성하세요
select 
    MST.POL_CD,
    CNTR.CNTR_TYPE,
    COUNT(CNTR.CNTR_NO) AS CNTR_COUNT,
    SUM(CNTR.CNTR_WGT) AS TOTAL_WGT
FROM
    FMS_HBL_MST MST
JOIN 
    FMS_HBL_CNTR CNTR ON MST.HBL_NO =CNTR.HBL_NO
WHERE 
    -- MST.ETD 2025.05.01 또는 20250511 사이에 데이터를 출력
    MST.ETD >= '20250501' AND MST.ETD <= '20250511'
GROUP BY
    MST.POL C,
    CNTR.CNTR_TYPE
ORDER BY
    MST.POL_CD ASC,
    CNTR.CNTR_TYPE ASC;